version: '3.8'

services:

  rabbitmq:
    image: "rabbitmq:4.0-management"
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_network

  redis-server:
    image: "redis"
    restart: unless-stopped
    ports: 
      - "6379:6379"
    networks:
      - app_network

  server:
    build: "./server"
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on: [
      rabbitmq,
      redis-server
    ]

  submission-worker:
    build: ./submission_worker
    restart: unless-stopped
    scale: 1
    depends_on: [
      rabbitmq,
      redis-server]
    networks:
      - app_network
  
  execution-worker:
    build: ./execution_worker
    restart: unless-stopped
    scale: 1
    depends_on: [
      rabbitmq,
      redis-server]
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
