"""initial migrations

Revision ID: d7eb9f257ace
Revises: 
Create Date: 2025-05-10 21:26:56.461347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7eb9f257ace'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('submissions_question_id_fkey', 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'questions', ['question_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key('submissions_question_id_fkey', 'submissions', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###
